In [3]:
import numpy as np

Alright lets get some basics going


In [4]:
architecture=np.random.randint(np.random.randint(1,2),np.random.randint(2,10),np.random.randint(3,8))
numlayer=len(architecture)
architecture

array([4, 5, 2, 5])

In [5]:
input=np.random.randn(architecture[0])
input

array([ 0.85736713, -0.77751988,  0.13371797, -0.47003173])

In [6]:
def genweights(architecture):
    W=[]
    for i in range(1,len(architecture)):
        W.append(np.random.randn(architecture[i],architecture[i-1]))

    return W

Weight=genweights(architecture)
Weight

[array([[ 1.15497344,  1.98705459, -0.28013643,  1.29088643],
        [-2.62649307,  0.05184967,  0.36980903,  0.0851527 ],
        [ 1.48334935,  0.86636424, -1.58733794,  0.32361609],
        [ 1.65792923, -0.5754542 , -0.20447966,  1.41190645],
        [-1.78963225,  0.9370594 ,  0.7145352 , -1.36868756]]),
 array([[ 0.37127801, -1.38256653, -0.75980039, -0.74027412,  0.33147945],
        [ 1.0430414 ,  1.96844427, -0.01063132, -0.79719881,  0.1169308 ]]),
 array([[ 0.45865264,  0.32804725],
        [-1.04245767, -0.54894925],
        [ 0.97860477,  0.44174125],
        [ 0.96744128, -0.74759844],
        [ 1.17652017,  1.50841352]])]

In [7]:
def genbias(architecture):
    B=[]
    for i in range(1,len(architecture)):
        B.append(np.random.randn(architecture[i]))
    return B

Biases=genbias(architecture)
Biases

[array([ 0.81083484, -1.44280168,  1.88566304, -0.14977054, -0.64291363]),
 array([-0.68075195,  0.2835621 ]),
 array([-0.78880952,  0.08023699,  1.92371125, -0.8949418 , -0.10836262])]

In [8]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [9]:
def sigmoidlist(array):
    b=[]
    for i in range(len(array)):
        b.append(sigmoid(array[i]))
    
    return b




In [10]:
A=[]
Z=[]

In [11]:
def forward(input,architecture,A,Z):
    Z.append(np.dot(Weight[0],input.T)+Biases[0])
    l=architecture[1]
    A.append(sigmoidlist(Z))
    for i in range(1,numlayer-1):
        Z.append(np.dot(A[i-1],np.transpose(Weight[i]))+Biases[i])
        A.append(sigmoidlist(Z[-1]))
    


In [12]:
forward(input,architecture,A,Z)


In [13]:
A

[[array([0.40416991, 0.0235325 , 0.89277998, 0.73655264, 0.10275375])],
 [array([0.14770037, 0.5416024 ])],
 [array([0.36739813, 0.40828814, 0.90949626, 0.23922166, 0.70731315])]]

In [14]:
Z

[array([-0.3881202 , -3.72555901,  2.11945716,  1.02812714, -2.16699503]),
 array([[-1.75275248,  0.16679523]]),
 array([[-0.54339518, -0.37104663,  2.30749965, -1.15695147,  0.88237022]])]

In [15]:
def cost_of_neuron(target,output):
    cost =((target-output)**2)/2
    return cost

In [16]:
def cost_of_network(target,output):
    cost=0
    l=len(target)
    for i in range(l):
        cost+=((target[i]-output[i])**2)/2
    return cost


In [17]:
def loss(cost_network,length):
    if length==1:
        loss=cost_network
    else:
        loss=cost_network/len

    return loss
    


In [18]:
def gradA(target,A,layer):
    dA=[]
    for i in range(len(A[layer])):
     dA.append(A[layer][i]-target[i])
    return dA


In [19]:
def gradZ(gradA,Z,A,layer):
    dZ=[]
    for i in range(len(Z)):
        dZ.append(gradA[i]*A[layer][i]*(1/np.exp(Z[layer][i])+1))
    return dZ

In [20]:
def gradB(gradZ):
    return gradZ

In [21]:
def gradA_1(gradZ,Weight,layer):
    return np.multiply(gradZ,Weight[layer])

In [22]:
def gradW(gradZ,A,layer):
    return np.multiply(np.transpose(gradZ),A[layer-1])
    

In [23]:
class Network:
    pass
